### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by hwittenborn** [makedeb/mist#15]
The goal of this project is to eventually be a fully-fleshed MPR helper, with support for things like installing and updating packages (from both APT repos and the MPR). Likewise, I'd like to rename this project to something new, as doing something like `sudo mpr install build-essential` doesn't make much sense, considering that it's installing an APT package.

If anyone has any project name ideas, feel free to leave them below.

**Comment by hwittenborn** [comment]
Basic ideas off the top of my head,

- `xpm` - Cross-platform (Apt + MPR) package manager
- `mpm` - Big classic
- `tap` - Big classic

They don't have to symbolize anything either, I just want a name that flows well.

**Comment by Henryws** [comment]
`xpm` sounds nice.

**Comment by hwittenborn** [comment]
I did some thinking, and I think I'm gonna go with `mist`. Doesn't seem like it's being used anywhere else either.

**Comment by hwittenborn** [comment]
Gonna reopen this, being before 1.0 gives the wonderful opportunity to rename the project a million times.

Two more ideas I want to consider:

- `mari`
- `muri`

**Comment by hwittenborn** [comment]
I think I'm gonna go with `mari`, this should hopefully be the last time things change like this.

**Comment by hwittenborn** [comment]
Looks like I'm gonna settle on Mist again :P. I think this should be final now though.
