### ISSUE TITLE
called `Option::unwrap()` on a `None` value', src/cache.rs:268:43

### ISSUE THREAD

**Issue by jrop** [makedeb/mist#27]
After a fresh install of `mist`, I am getting the following panic:

```sh
❯ mist search just
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cache.rs:268:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
❯
```

**Comment by hwittenborn** [comment]
Hey, thanks for the issue report!

Could you send the following information over?

- Distro
- Distro Version
- Any extra APT repositories set up on your system

**Comment by jrop** [comment]
Distro: Pop_OS!
Version: Pop!_OS 22.04 LTS
Other APT repositories: (not sure if the following answers your question or not)
```
❯ ls /etc/apt/sources.list.d
archive_uri-https_apt_releases_hashicorp_com-impish.list.save
brave-browser-release.list
brave-browser-release.list.save
google-chrome.list
google-chrome.list.save
makedeb.list
ngrok.list
ngrok.list.save
pop-os-apps.sources
pop-os-apps.sources.save
pop-os-release.sources
pop-os-release.sources.save
system.sources
system.sources.save
tailscale.list
tailscale.list.save
```
(it honestly looks as though I might want to cull that :thinking: a bit)

**Comment by hwittenborn** [comment]
Thanks! I'm suspecting it's one of those repositories (maybe the Brave, Google Chrome, or ngrok one), but I wouldn't really be able to know until I do some testing myself. I'm currently working on #22 right now though, and I probably won't be working on must else with Mist until that's complete, but it's just awaiting one more feature to arrive in the APT library Mist uses, and then it should be merged shortly after. Hopefully that's within the next week or so, but I can't really give a reliable estimate.

**Comment by hwittenborn** [comment]
Hey! I've gotten #22 merged now, could you see if the issue keeps happening still after updating your version of Mist?

**Comment by jrop** [comment]
That appears to fix my issue.  Thanks!
